// Package caddy renders the front for the blue-green pair and knows how to
// read/flip the live upstream. hadi owns /etc/caddy/hadi/<name>.caddy; the
// main Caddyfile just imports that directory, so several services share a box
// without clobbering each other.
package caddy

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/mitteai/hadi/internal/config"
)

// MainCaddyfile is the whole /etc/caddy/Caddyfile under hadi.
//
// trusted_proxies: LB-fronted services receive traffic from the Hetzner LB
// over the private network. Without trusting those peers, Caddy OVERWRITES
// the LB's X-Forwarded-Proto/-For with its own view (proto http, IP = the
// LB's), which broke Google OAuth on mitte.ai (redirect_uri generated as
// http://) and hid real client IPs from every service. private_ranges is
// safe: only the LBs and fleet boxes live there, and Caddy still overwrites
// forwarded headers from any public, untrusted peer.
const MainCaddyfile = "# GENERATED BY hadi — per-service sites live in /etc/caddy/hadi/\n" +
	"{\n\tservers {\n\t\ttrusted_proxies static private_ranges\n\t}\n}\n" +
	"import /etc/caddy/hadi/*.caddy\n"

// SitePath is where a service's site config lives on the box.
func SitePath(name string) string { return "/etc/caddy/hadi/" + name + ".caddy" }

// RenderSite produces the site config with the given upstream color live.
func RenderSite(c *config.Config, activeColor int) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	w("# GENERATED BY hadi — deploys rewrite the upstream port (%d <-> %d) and reload.", c.Colors[0], c.Colors[1])
	if c.Entry.Domain != "" {
		// Public entry: Caddy terminates TLS, obtains and renews the
		// certificate automatically. Nobody thinks about certs again.
		w("%s {", c.Entry.Domain)
	} else {
		w(":%d {", c.Entry.Port)
	}
	if c.Entry.BodyMax != "" {
		w("\trequest_body {")
		w("\t\tmax_size %s", c.Entry.BodyMax)
		w("\t}")
	}
	w("\treverse_proxy 127.0.0.1:%d {", activeColor)
	if c.Entry.ProxyTimeout != "" {
		w("\t\ttransport http {")
		w("\t\t\tread_timeout %s", c.Entry.ProxyTimeout)
		w("\t\t\twrite_timeout %s", c.Entry.ProxyTimeout)
		w("\t\t}")
	}
	w("\t}")
	w("}")
	return b.String()
}

// ActiveColor parses which color a rendered config (site file, or any caddy
// config text found on a box) currently points at.
func ActiveColor(text string, c *config.Config) (int, error) {
	re := regexp.MustCompile(`127\.0\.0\.1:(` + strconv.Itoa(c.Colors[0]) + `|` + strconv.Itoa(c.Colors[1]) + `)`)
	m := re.FindStringSubmatch(text)
	if m == nil {
		return 0, fmt.Errorf("no blue-green upstream (%d or %d) found in caddy config", c.Colors[0], c.Colors[1])
	}
	port, _ := strconv.Atoi(m[1])
	return port, nil
}
