// Package unit renders the systemd template unit from deploy.json — the
// load-bearing design choice: one blessed template in one codebase, so the
// whole class of "repo unit disagrees with box unit" bugs dies.
package unit

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mitteai/hadi/internal/config"
)

// Render produces <name>@.service. %i is the listen port.
func Render(c *config.Config) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	w("# GENERATED BY hadi — do not edit on the box; change deploy.json instead.")
	w("[Unit]")
	w("Description=%s (port %%i, hadi blue-green)", c.Name)
	after := append([]string{"network-online.target"}, c.Run.After...)
	after = append(after, c.Run.Requires...)
	w("After=%s", strings.Join(after, " "))
	if len(c.Run.Requires) > 0 {
		w("Requires=%s", strings.Join(c.Run.Requires, " "))
	}
	w("Wants=network-online.target")
	w("")
	w("[Service]")
	w("Type=simple")
	w("User=%s", c.Run.User)
	w("Group=%s", c.Run.User)
	w("EnvironmentFile=-/etc/%s/env", c.Name)
	// The port must win over the env file, which is why the env file must
	// never contain the port variable (hadi env refuses to ship one that does).
	w("Environment=%s=%%i", c.Run.PortEnv)
	for _, k := range sortedKeys(c.Run.EnvExtra) {
		w("Environment=%s=%s", k, c.Run.EnvExtra[k])
	}
	w("ExecStart=%s", c.Run.Exec)
	w("WorkingDirectory=/opt/%s/current", c.Name)
	w("Restart=always")
	w("RestartSec=2")
	w("")
	w("KillSignal=SIGTERM")
	w("TimeoutStopSec=%d", c.Run.StopTimeout)
	w("")
	w("ProtectSystem=strict")
	w("ProtectHome=true")
	w("PrivateTmp=true")
	if len(c.Run.AmbientCaps) == 0 {
		w("NoNewPrivileges=true")
	}
	if len(c.Run.ReadWritePath) > 0 {
		w("ReadWritePaths=%s", strings.Join(c.Run.ReadWritePath, " "))
	}
	if len(c.Run.AmbientCaps) > 0 {
		w("AmbientCapabilities=%s", strings.Join(c.Run.AmbientCaps, " "))
		w("CapabilityBoundingSet=%s", strings.Join(c.Run.AmbientCaps, " "))
	}
	if len(c.Run.Delegate) > 0 {
		w("Delegate=%s", strings.Join(c.Run.Delegate, " "))
	}
	w("LimitNOFILE=65536")
	w("")
	w("[Install]")
	w("WantedBy=multi-user.target")
	return b.String()
}

// sortedKeys keeps renders deterministic (map order is random).
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
