// Package unit renders the systemd template unit from deploy.json — the
// load-bearing design choice: one blessed template in one codebase, so the
// whole class of "repo unit disagrees with box unit" bugs dies.
package unit

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mitteai/hadi/internal/config"
)

// UIDToken and GIDToken are placeholders in image units, substituted box-side
// at install time (`id -u/-g <run.user>`): the render is pure local string
// building and must not guess uids, and %U in system units resolves to the
// MANAGER's user (root), never User=.
const (
	UIDToken = "{{UID}}"
	GIDToken = "{{GID}}"
)

// Render produces <name>@.service. %i is the listen port.
func Render(c *config.Config) string {
	if c.IsImage() {
		return renderImage(c)
	}
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	w("# GENERATED BY hadi — do not edit on the box; change deploy.json instead.")
	w("[Unit]")
	w("Description=%s (port %%i, hadi blue-green)", c.Name)
	after := append([]string{"network-online.target"}, c.Run.After...)
	after = append(after, c.Run.Requires...)
	w("After=%s", strings.Join(after, " "))
	if len(c.Run.Requires) > 0 {
		w("Requires=%s", strings.Join(c.Run.Requires, " "))
	}
	w("Wants=network-online.target")
	w("")
	w("[Service]")
	w("Type=simple")
	w("User=%s", c.Run.User)
	w("Group=%s", c.Run.User)
	w("EnvironmentFile=-/etc/%s/env", c.Name)
	// The port must win over the env file, which is why the env file must
	// never contain the port variable (hadi env refuses to ship one that does).
	w("Environment=%s=%%i", c.Run.PortEnv)
	for _, k := range sortedKeys(c.Run.EnvExtra) {
		w("Environment=%s=%s", k, c.Run.EnvExtra[k])
	}
	// systemd requires an absolute ExecStart. A relative exec (release
	// tarballs: "bin/server") is anchored to the current-release symlink,
	// which the deploy repoints before restarting the color.
	exec := c.Run.Exec
	if !strings.HasPrefix(exec, "/") {
		exec = fmt.Sprintf("/opt/%s/current/%s", c.Name, exec)
	}
	w("ExecStart=%s", exec)
	w("WorkingDirectory=/opt/%s/current", c.Name)
	w("Restart=always")
	w("RestartSec=2")
	w("")
	w("KillSignal=SIGTERM")
	w("TimeoutStopSec=%d", c.Run.StopTimeout)
	w("")
	w("ProtectSystem=strict")
	w("ProtectHome=true")
	w("PrivateTmp=true")
	if len(c.Run.AmbientCaps) == 0 {
		w("NoNewPrivileges=true")
	}
	if len(c.Run.ReadWritePath) > 0 {
		w("ReadWritePaths=%s", strings.Join(c.Run.ReadWritePath, " "))
	}
	if len(c.Run.AmbientCaps) > 0 {
		w("AmbientCapabilities=%s", strings.Join(c.Run.AmbientCaps, " "))
		w("CapabilityBoundingSet=%s", strings.Join(c.Run.AmbientCaps, " "))
	}
	if len(c.Run.Delegate) > 0 {
		w("Delegate=%s", strings.Join(c.Run.Delegate, " "))
	}
	w("LimitNOFILE=65536")
	w("")
	w("[Install]")
	w("WantedBy=multi-user.target")
	return b.String()
}

// renderImage is the image-kind branch of the one blessed template: the same
// blue-green contract (per-color port, env file, SIGTERM drain) expressed as a
// rootful podman container. Flag choices proven on noble/podman 4.9.3
// (spike 2026-07-15, docs/proposals/hadi-image-artifacts.md):
//   - Type=notify + --sdnotify=conmon: "started" means the container is up
//   - --cgroups=split: conmon + container processes live in the unit's cgroup,
//     so systemctl stop / KillSignal / TimeoutStopSec mean what flip assumes
//   - --log-driver=passthrough: without it every app line lands in journald
//     twice (podman relay + conmon both write)
//   - --pull=never + localhost/ tag: never consult a registry
//   - ExecStop's "-" prefix: on a cross-kind migration deploy the old color is
//     a plain process, podman stop finds no container, and systemd must fall
//     through to KillSignal instead of flagging the unit failed
func renderImage(c *config.Config) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	w("# GENERATED BY hadi — do not edit on the box; change deploy.json instead.")
	w("[Unit]")
	w("Description=%s (port %%i, hadi blue-green, image)", c.Name)
	after := append([]string{"network-online.target"}, c.Run.After...)
	after = append(after, c.Run.Requires...)
	w("After=%s", strings.Join(after, " "))
	if len(c.Run.Requires) > 0 {
		w("Requires=%s", strings.Join(c.Run.Requires, " "))
	}
	w("Wants=network-online.target")
	w("")
	w("[Service]")
	w("Type=notify")
	w("NotifyAccess=all")

	// Privilege drop happens inside the container (--user + --cap-drop), not
	// via User=: rootful podman is what keeps the orchestration (root over
	// SSH) and the unit looking at the same image storage.
	run := []string{
		"/usr/bin/podman run --rm --replace --name " + c.Name + "-%i",
		"--sdnotify=conmon --cgroups=split --pull=never --log-driver=passthrough",
		"--network host",
		fmt.Sprintf("--user %s:%s", UIDToken, GIDToken),
		"--cap-drop=all",
	}
	if len(c.Run.AmbientCaps) > 0 {
		for _, cap := range c.Run.AmbientCaps {
			run = append(run, "--cap-add="+strings.TrimPrefix(cap, "CAP_"))
		}
	} else {
		run = append(run, "--security-opt no-new-privileges")
	}
	for _, p := range c.Run.ReadWritePath {
		run = append(run, fmt.Sprintf("-v %s:%s", p, p))
	}
	run = append(run,
		fmt.Sprintf("--env-file /etc/%s/env", c.Name),
		fmt.Sprintf("--env %s=%%i", c.Run.PortEnv),
	)
	for _, k := range sortedKeys(c.Run.EnvExtra) {
		run = append(run, fmt.Sprintf("--env %s=%s", k, c.Run.EnvExtra[k]))
	}
	run = append(run,
		fmt.Sprintf("--stop-timeout %d", c.Run.StopTimeout),
		fmt.Sprintf("%s:current", c.BoxImage()),
	)
	w("ExecStart=%s", strings.Join(run, " \\\n  "))
	w("ExecStop=-/usr/bin/podman stop %s-%%i", c.Name)
	w("Restart=always")
	w("RestartSec=2")
	w("")
	w("KillSignal=SIGTERM")
	// +5s so podman's own stop timeout always wins before systemd escalates.
	w("TimeoutStopSec=%d", c.Run.StopTimeout+5)
	// Conmon notifies on container-up (fast, local image); app readiness is
	// the engine's health loop, not the start job.
	w("TimeoutStartSec=30")
	if len(c.Run.Delegate) > 0 {
		w("Delegate=%s", strings.Join(c.Run.Delegate, " "))
	}
	w("LimitNOFILE=65536")
	w("")
	w("[Install]")
	w("WantedBy=multi-user.target")
	return b.String()
}

// sortedKeys keeps renders deterministic (map order is random).
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
